spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anshu-vijay/Microservices-Config
          clone-on-start: true

server:
  port: 8085

