server:
  port: 8082

spring:
  application:
    name: RATING-SERVICE
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/micorservices
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8085/
  cloud:
    compatibility-verifier:
      enabled: false

  #Handled using config server with the configurations present on github
  #eureka:
  #  instance:
  #    prefer-ip-address: true
  #  client:
  #    fetch-registry: true
  #    register-with-eureka: true
  #    service-url:
  #      defaultZone: http://localhost:8761/eureka





