

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8085/
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATINGSERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
server:
  port: 8084
